import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;















        /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * register.java
 *
 * Created on Oct 28, 2018, 5:50:25 PM
 */

/**
 *
 * @author ganesh
 */
public class register extends javax.swing.JFrame {

    /** Creates new form register */
    public register() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEW MOVIE.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(290, 280, 107, 20);

        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 290, 27, 14);
        getContentPane().add(tf2);
        tf2.setBounds(280, 330, 106, 20);

        Username.setText("Username");
        getContentPane().add(Username);
        Username.setBounds(160, 340, 48, 14);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 380, 46, 14);
        getContentPane().add(tf3);
        tf3.setBounds(280, 370, 106, 20);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 410, 86, 14);
        getContentPane().add(tf4);
        tf4.setBounds(280, 410, 106, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NEW MOVIE.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, -10, 520, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

         private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
             // TODO add your handling code here:
         }//GEN-LAST:event_tf1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables

}
